### ISSUE TITLE
Timeout après 15 minutes d'inactivité

### ISSUE THREAD

**Issue by Taloud** [SocialGouv/dila-api-client#134]
Après avoir lancé mon API qui utilise dila api client, si je ne fais pas de requêtes pendant 15 ou 20 mins je suis timeout de Dila et je dois relancer mon api pour ravoir un token valide.

Je m'occupe de chercher d'ou vient le problème et je fais un PR pour essayer de le corriger.

**Comment by revolunet** [comment]
released in 1.1.1 : https://github.com/SocialGouv/dila-api-client/pull/137
